# Generated by Django 4.1.3 on 2022-11-27 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="cratedAt",
            new_name="crated_at",
        ),
    ]
